### ISSUE TITLE
Drawing Widget Suggestion 

### ISSUE THREAD

**Issue by hherrada** [daattali/advanced-shiny#6]
Hi! Thanks for all these great tools! I've been looking for a widget that would allow me to draw on an html canvas. Something like this: https://dev.opera.com/articles/html5-canvas-painting/example-5.html

Do you know of a shiny package that would allow me to do so?

**Comment by daattali** [comment]
No I do not. And I don't think there will ever be one... Embedding that canvas into a shiny app is not too hard to do, but I don't think that would ever be in a package. It doesn't seem like something that is widely applicable to shiny applications and I can't think of a way for this to interact with shiny.

If you really need that done you can contact me by email, but I'm closing this issue since it's not something I'll add to this list!
